<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3woagfn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3woagfn/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3woagfn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3woagfn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3woagfn\appProdProjectContainer([
    'container.build_hash' => '3woagfn',
    'container.build_id' => 'dd162ed5',
    'container.build_time' => 1636805663,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3woagfn');
