<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfcyuqm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfcyuqm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUfcyuqm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUfcyuqm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUfcyuqm\appProdProjectContainer([
    'container.build_hash' => 'Ufcyuqm',
    'container.build_id' => '01974da2',
    'container.build_time' => 1636744586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUfcyuqm');
