<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIcluhcy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIcluhcy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIcluhcy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIcluhcy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIcluhcy\appProdProjectContainer([
    'container.build_hash' => 'Icluhcy',
    'container.build_id' => '69b6a88f',
    'container.build_time' => 1636837963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIcluhcy');
