version: '3.3'

services:
   druzynaB:
     image: wercabaj/be_180061_new
     ports:
      - 18061:80
      - 18062:443
     restart: always
     networks:
      - admin-mysql_default
     environment:
       PS_INSTALL_AUTO: 0
       PS_ERASE_DB: 0
       DB_SERVER: actina15.maas
       DB_USER: BE_180061
       DB_PASSWD: password
       DB_NAME: BE_180061
       PS_DEV_MODE: 0
       PS_DOMAIN: localhost:18061
       PS_DOMAIN_SSL: localhost:18062
       PS_FOLDER_ADMIN: admin
networks:
    admin-mysql_default:
     external:
      name: admin-mysql_default
