services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
      - ./db-dumps:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db

   prestashop:
     depends_on:
       - db
     image: prestashop/prestashop:1.7.2.4
     ports:
       - "80:80"
     restart: always
     environment:
       PS_INSTALL_AUTO: 0
       PS_ERASE_DB: 0
       DB_SERVER: db
       DB_USER: root
       DB_PASSWD: root
       DB_NAME: db
       PS_DEV_MODE: 0
       PS_DOMAIN: localhost:80
       PS_FOLDER_ADMIN: admin
       PS_FOLDER_INSTALL: install
     volumes:
       - ./shop-data:/var/www/html

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     environment:
       PMA_HOST: db