<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2vsvhb0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2vsvhb0/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2vsvhb0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2vsvhb0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2vsvhb0\appProdProjectContainer([
    'container.build_hash' => '2vsvhb0',
    'container.build_id' => '9281ed9a',
    'container.build_time' => 1636805630,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2vsvhb0');
