<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWqjoym3\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWqjoym3/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWqjoym3.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWqjoym3\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWqjoym3\appProdProjectContainer([
    'container.build_hash' => 'Wqjoym3',
    'container.build_id' => '592f8cd6',
    'container.build_time' => 1634572310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWqjoym3');
