<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrxyxdq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrxyxdq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLrxyxdq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLrxyxdq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLrxyxdq\appProdProjectContainer([
    'container.build_hash' => 'Lrxyxdq',
    'container.build_id' => '80c9e509',
    'container.build_time' => 1634572454,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrxyxdq');
